# Generated by Django 5.1.3 on 2024-11-06 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign_id",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("campaign_name", models.CharField(max_length=128)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("SEARCH_STANDARD", "Search Standard"),
                            ("VIDEO_RESPONSIVE", "Video Responsive"),
                        ],
                        max_length=128,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
