# Generated by Django 5.1.3 on 2024-11-06 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ad_group", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdGroupStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("MOBILE", "Mobile"),
                            ("TABLET", "Tablet"),
                            ("DESKTOP", "Desktop"),
                        ],
                        max_length=128,
                    ),
                ),
                ("impressions", models.IntegerField()),
                ("clicks", models.IntegerField()),
                ("conversions", models.DecimalField(decimal_places=10, max_digits=22)),
                ("cost", models.DecimalField(decimal_places=10, max_digits=22)),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ad_group.adgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
