# Generated by Django 5.1.3 on 2024-11-06 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ad_group_id",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ad_group_name", models.CharField(max_length=128)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaign.campaign",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
