# Generated by Django 5.1.3 on 2024-11-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedtracker",
            name="seeded",
            field=models.BooleanField(default=True),
        ),
    ]
